<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <IsPackable>false</IsPackable>
        <RootNamespace>StealthSharp.MockServer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\StealthSharp.Abstract\StealthSharp.Abstract.csproj" />
        <ProjectReference Include="..\StealthSharp.Serialization\StealthSharp.Serialization.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    </ItemGroup>

</Project>
